syntax = "proto3";

package common.v1;

// --------------------------------------------------
// Pagination
// --------------------------------------------------

message PageRequest {
  uint32 page_size  = 1;
  string page_token = 2;
}

message PageResponse {
  string next_page_token = 1;
}

// --------------------------------------------------
// Errors
// --------------------------------------------------

message FieldViolation {
  string field       = 1;
  string description = 2;
}

message ErrorDetails {
  string                  code             = 1;
  string                  message          = 2;
  repeated FieldViolation field_violations = 3;
}

// --------------------------------------------------
// Generic operation response
// --------------------------------------------------

message Empty {
}

// --------------------------------------------------
// Service metadata
// --------------------------------------------------

message ServiceInfo {
  string service_name = 1;
  string version      = 2;
}